---
title: "Time series analysis & forecasting using R"
venue: Columbia University, New York City
author: "Rob J Hyndman and Mitchell O'Hara-Wild"
format: markdown
---

## Dates

11-12 July 2023

## Course description

It is becoming increasingly common for organizations to collect huge amounts of data over time, and existing time series analysis tools are not always suitable to handle the scale, frequency and structure of the data collected. In this workshop, we will look at some packages and methods that have been developed to handle the analysis of large collections of time series.

On day 1, we will look at the tsibble data structure for flexibly managing collections of related time series. We will look at how to do data wrangling, data visualizations and exploratory data analysis. We will explore feature-based methods to explore time series data in high dimensions. A similar feature-based approach can be used to identify anomalous time series within a collection of time series, or to cluster or classify time series. Primary packages for day 1 will be [tsibble](https://cran.r-project.org/package=tsibble), [lubridate](https://cran.r-project.org/package=lubridate) and [feasts](https://cran.r-project.org/package=feasts) (along with the [tidyverse](http://tidyverse.org) of course).

Day 2 will be about forecasting. We will look at some classical time series models and how they are automated in the [fable](https://cran.r-project.org/package=fable) package. We will look at creating ensemble forecasts and hybrid forecasts, as well as some new forecasting methods that have performed well in large-scale forecasting competitions. Finally, we will look at forecast reconciliation, allowing millions of time series to be forecast in a relatively short time while accounting for constraints on how the series are related.

## Learning objectives

Attendees will learn:

1. How to wrangle time series data with familiar tidy tools.
2. How to compute time series features and visualize large collections of time series.
3. How to select a good forecasting algorithm for your time series.
4. How to ensure forecasts of a large collection of time series are coherent.

## Is this course for me?

This course will be appropriate for you if you answer yes to these questions:

1. Do you already use R regularly, especially the tidyverse packages, or are willing to do suitable pre-course training in R and tidyverse?
2. Do you need to analyse large collections of related time series?
3. Would you like to learn how to use some new tidy tools for time series analysis including visualization, decomposition and forecasting?

## Prework

Participants should be familiar with the use of R, at least to the point where they can fit a linear regression model, and work with data frames.

People who don't use R regularly, or don't know the tidyverse packages, are recommended to do the tutorials at [learnr.numbat.space](http://learnr.numbat.space) beforehand.

Please bring your own laptop with a recent version of R and RStudio installed. The following code will install the main packages needed for the workshop.

```r
install.packages(c("tidyverse","fpp3","GGally", "sugrrants"))
```

## Schedule

| Time          | Activity         |
| :------------ | :--------------- |
| 09:00 - 10:30 | Session 1        |
| 10:30 - 11:00 | *Coffee break*   |
| 11:00 - 12:30 | Session 2        |
| 12:30 - 13:30 | *Lunch break*    |
| 13:30 - 15:00 | Session 3        |
| 15:00 - 15:30 | *Coffee break*   |
| 15:30 - 17:00 | Session 4        |

## Slides

### Day 1

  0. [Background](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/0-intro.pdf)
  1. [Introduction to tsibbles](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/1-tsibbles.pdf)
  2. [Time series graphics](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/2-graphics.pdf)
  3. [Transformations](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/3-transformations.pdf)
  4. [Seasonality and trends](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/4-decompositions.pdf)
  5. [Time series features](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/5-feasts.pdf)

### Day 2

  6. [Introduction to forecasting](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/6-fable.pdf)
  7. [Exponential smoothing](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/7-ets.pdf)
  8. [ARIMA models](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/8-arima.pdf)
  9. [Dynamic regression](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/9-dynamic-regression.pdf)
  10. [Hierarchical forecasting](https://github.com/robjhyndman/forecasting_workshop/raw/NYC/10-reconciliation.pdf)

## [Labs](https://github.com/robjhyndman/forecasting_workshop/blob/main/Labs.md)
